### ISSUE TITLE
C Programming

### ISSUE THREAD

**Issue by 16BEM0073** [IEEECS-VIT/IEEECS-VIT-Website#11]
Could you please suggest a good book for learning the basics of C programming?

**Comment by Vishwajeetsinh98** [comment]
[Teach yourself C by Herbert Schildt](http://www.amazon.in/Teach-Yourself-C-Herbert-Schildt/dp/0078823110) is a good book to get started.

**Comment by 16BEM0073** [comment]
Thanks

**Comment by Vishwajeetsinh98** [comment]
Thank you for reaching us.
